avoid maybe-uninitialized in PowerPointShapeExport
/home/noel/libo3/sd/source/filter/eppt/pptx-epptooxml.cxx: In member
function ‘oox::drawingml::ShapeExport&
oox::core::PowerPointShapeExport::WritePlaceholderReferenceTextBody(oox::core::PlaceholderType,
PageType,
com::sun::star::uno::Reference<com::sun::star::beans::XPropertySet>)’:
/home/noel/libo3/sd/source/filter/eppt/pptx-epptooxml.cxx:1715:31:
error: ‘nDateTimeFormat’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
1715 |                 SvxTimeFormat eTime =
static_cast<SvxTimeFormat>(nDateTimeFormat >> 4);
      |                               ^~~~~
/home/noel/libo3/sd/source/filter/eppt/pptx-epptooxml.cxx:1707:36:
error: ‘bIsDateTimeFixed’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
 1707 |             if(ePageType != LAYOUT && !bIsDateTimeFixed)
      |                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~

Change-Id: I7f622321680705fb0b0fa42630949c8d6af8488e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/117398
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
(cherry picked from commit 3c24e7ed972ae2fc431365e4884e27c0b243c905)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/117643
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>